### ISSUE TITLE
where do i get the captcha api key?

### ISSUE THREAD

**Issue by superfastisfast** [H4cK3dR4Du/Discord-Member-Booster#5]
title

**Comment by ksIsCute** [comment]
https://capmonster.cloud/Dashboard

**Comment by superfastisfast** [comment]
right, but is it free?

**Comment by ksIsCute** [comment]
nah but u can spend like a dollar and geet like 3k tokens and members lfmao

**Comment by superfastisfast** [comment]
fine, ill code it myself using whisper

**Comment by superfastisfast** [comment]
ill send when i am done, i think its free..

**Comment by superfastisfast** [comment]
# Import the required modules
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time
import json
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import requests
import os
import whisper
import warnings
warnings.filterwarnings("ignore")

model = whisper.load_model("base")

def transcribe(url):
    with open('.temp', 'wb') as f:
        f.write(requests.get(url).content)
    result = model.transcribe('.temp')
    return result["text"].strip()

def click_checkbox(driver):
    driver.switch_to.default_content()
    driver.switch_to.frame(driver.find_element(By.XPATH, ".//iframe[@title='reCAPTCHA']"))
    driver.find_element(By.ID, "recaptcha-anchor-label").click()
    driver.switch_to.default_content()

def request_audio_version(driver):
    driver.switch_to.default_content()
    driver.switch_to.frame(driver.find_element(By.XPATH, ".//iframe[@title='recaptcha challenge expires in two minutes']"))
    driver.find_element(By.ID, "recaptcha-audio-button").click()

def solve_audio_captcha(driver):
    text = transcribe(driver.find_element(By.ID, "audio-source").get_attribute('src'))
    driver.find_element(By.ID, "audio-response").send_keys(text)
    driver.find_element(By.ID, "recaptcha-verify-button").click()

if __name__ == "__main__":
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install())
  
    driver.get("https://www.google.com/recaptcha/api2/demo")
    click_checkbox(driver)
    time.sleep(1)
    request_audio_version(driver)
    time.sleep(1)
    solve_audio_captcha(driver)
    time.sleep(10)
    
   found something useful

**Comment by ksIsCute** [comment]
what is that

**Comment by superfastisfast** [comment]
its a whisper captcha transciber

**Comment by ksIsCute** [comment]
does discord use it?

**Comment by ksIsCute** [comment]
File "C:\Users\willi\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by superfastisfast** [comment]
no recaptchas have an audio thingy right, use the audio thingy, and download the mp3 file, use whisper to transcribe delete the mp3 file to keep it clean, and type the text

**Comment by lonewolf-github** [comment]
> no recaptchas have an audio thingy right, use the audio thingy, and download the mp3 file, use whisper to transcribe delete the mp3 file to keep it clean, and type the text

discord uses hcaptcha though lol

**Comment by NxyyLOL** [comment]
and hcaptcha = no audio lmao, learn your history first

**Comment by superfastisfast** [comment]
didnt it use to use recap?
Im prob to dumb to do anything but i finished the whisper thing

**Comment by Viqni** [comment]
> nah but u can spend like a dollar and geet like 3k tokens and members lfmao

are those the tokens that work for the member bot? And if i add one does only 1 member join? And are these like pre-set accs like i dont get how tht works? (sorry for alot of questions lmao)
